name: Deploy porteFolio-V2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH test
        uses: appleboy/ssh-action@master
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/portefolio_astro
            sudo git pull
            sudo npm install
            sudo npm run build
